Repository CarletonURocketry/packager, pull requests merged in 2023-11, with the labels that each got.

#30 Change Doxygen generation to only happen when a pull request is merged.
  .github/workflows/doxygen.yaml
Labels: documentation, enhancement

#31 Read stdin
  packager.use
  src/main.c
Labels: enhancement

#34 Blocks and packets
  src/include/packet_types.h
  src/main.c
  src/packet_types.c
Labels: enhancement

#33 Added acceleration data block.
  src/include/packet_types.h
  src/packet_types.c
Labels: enhancement

#36 Little endianness as per specification
  src/include/packet_types.h
  src/main.c
  src/packet_types.c
Labels: bug

#40 Doxygen updates
  Doxyfile
  doxygen-custom/custom.css
  doxygen-custom/footer.html
  inspacelogo.png
Labels: enhancement
